name: RDDLean

channels:
  # Keep sorted | Add at the bottom!
  - pytorch
  - pytorch-test
  - fastai
  - nvidia
  - defaults
  - conda-forge
  - numba
  - gpytorch
  - dglteam
  - pyviz
  - plotly
  - bokeh
  - cvxgrp
  - HuggingFace
  - fastchan
  - intel
  - nlesc

dependencies:
  # PINNED

  # System
  - python=3.9.7
  - cudatoolkit=11.3
  - magma-cuda113>=2.5.2
  - blas=*.*=mkl

  # PyTorch stack
  - pytorch>=1.10
  - torchvision>=0.11.1
  - torchaudio>=0.10
  - torchtext>=0.11
  - torchserve>=0.4.2
  - torch-model-archiver>=0.4.2
  - torch-workflow-archiver>=0.1.2
  - gpytorch>=1.5.1
  - botorch>=0.5.1
  - ignite>=0.4.7
  - captum>=0.4

  # Vaex
  - vaex>=4.5 # Latest
  - vaex-core>=4.5 # Same as vaex
  - vaex-astro>=0.8.3 # Pinned to >= 0.8.3 by vaex
  - vaex-hdf5>=0.10 # Latest compatible with latest vaex
  - vaex-viz>=0.5 # Latest
  - vaex-jupyter>=0.6 # Latest
  - vaex-server>=0.6 # Latest compatible with latest vaex
  - vaex-ml>=0.9 # Pinned at >= 0.9

  # Misc
  - opt_einsum>=3.3
  - onnx>=1.10.2
  - tensorboard>=2.6
  - tensorboardx>=2.4 # Was pinned by (?) at =2.4
  - dgl-cuda11.3>=0.7.2
  - jupyterlab>=3.2.1
  - notebook>=6.4.5
  - black>=21.7b0
  - nb_black>=1.0.7
  - mlflow>=1.20.2
  - pip>=20.3.4 # Do not change!
  - pip-tools>=5.5 # Do not change!
  - numba>=0.54.1
  - fastprogress>=1

  # UNPINNED

  # System
  - conda
  - mkl-service
  - mkl
  - mkl_fft
  - mkl_random
  - intel-openmp

  # Install easers
  - importlib_metadata
  - setuptools
  - wheel
  - pep517

  # Scientific stack
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - scikit-optimize
  - seaborn
  - statsmodels
  - sympy
  - scikit-plot
  - scikit-geometry
  - networkx

  # Jupyter
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_launcher
  - jupyterlab_server
  - nb_conda_kernels
  - nbclient
  - nbconvert
  - nbformat
  - widgetsnbextension
  - ipyparallel
  - jupyter_nbextensions_configurator
  - ipygany
  - nbval

  # FFIs
  - cffi
  - pybind11
  - swig

  # Typing / Development aids
  - mypy
  - ipdb
  - ptvsd
  - pylint
  - mypy_extensions
  - typed-ast
  - typing_extensions

  # Misc
  - async-timeout
  - atomicwrites
  - attrdict
  - attrs
  - azure-storage-blob
  - bayesian-optimization
  - boto3
  - bravado
  - bravado-core
  - cachetools
  - category_encoders
  - certifi
  - chardet
  - click
  - cmaes
  - colorama
  - colorlog
  - configparser
  - cython
  - dataclasses
  - decorator
  - docker-pycreds
  - faiss-gpu
  - filelock
  - frozendict
  - funcsigs
  - future
  - gitpython
  - google-api-core
  - google-auth
  - google-cloud-storage
  - googleapis-common-protos
  - gpustat
  - h5py
  - hdf5
  - hiplot
  - imageio
  - imbalanced-learn
  - iniconfig
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - libjpeg-turbo
  - libpng
  - more-itertools
  - msgpack-numpy
  - msgpack-python
  - multidict
  - multipledispatch
  - multiprocess
  - numexpr
  - nvidia-ml-py3
  - oauthlib
  - olefile
  - packaging
  - pandas-summary
  - parso
  - path.py
  - pathlib2
  - pillow
  - plotly
  - prometheus_client
  - prompt_toolkit
  - psutil
  - py3nvml
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyjwt
  - pyparsing
  - pyrsistent
  - pytest
  - pytest-runner
  - python-dateutil
  - pytz
  - pyzmq
  - regex
  - requests-file
  - requests-oauthlib
  - rsa
  - six
  - threadpoolctl
  - toml
  - toolz
  - tqdm
  - urllib3
  - visdom
  - watchdog
  - wcwidth
  - websocket-client

  # Pip dependencies
  - prettytable
  - pyyaml
  - autopage
  - cerberus
  - cliff
  - cmd2
  - deprecation
  - distlib
  - fastrlock
  - flatbuffers
  - furl
  - humanfriendly
  - idna
  - jsonpointer
  - makefun
  - munch
  - pathtools
  - pbr
  - promise
  - py-cpuinfo
  - pydot
  - pyhocon
  - pyperclip
  - rfc3987
  - ruamel.yaml
  - ruamel.yaml.clib
  - sentry-sdk
  - shortuuid
  - stevedore
  - termcolor
  - typeguard
  - urwid
  - virtualenv
  - webcolors
  - xxhash
  - python-xxhash
  - yaspin

  # init.sh dependencies (not included in pip dependencies)
  - googledrivedownloader
  - rdflib
  - yacs

  # Migrated from pip (in init.sh)
  - jedi>=0.18
  - contextlib2
  - pyrser
  - tokenizers
  - jsonargparse
  - rich

  # PIP #
  - pip:
      # Sort by dependency (~ toposort)
      # PINS:
      # - JAX:               Latest
      # - JaxLib:            Latest
      # - adabelief-pytorch: Latest
      #
      - opencv-python
      - git+https://github.com/pytorch/contrib.git
      - graphviz
      - https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.1.73+cuda11.cudnn82-cp39-none-manylinux2010_x86_64.whl
      - jax==0.2.25
      - wandb
      - onnxruntime-gpu
      - onnxruntime-tools
      - clearml
      - clearml-agent
      - clearml-session
      - git+https://github.com/pyro-ppl/pyro-api.git
      - git+https://github.com/pyro-ppl/pyro.git
      - git+https://github.com/pyro-ppl/numpyro.git
      - git+https://github.com/pyro-ppl/funsor.git
      - git+https://github.com/emaballarin/pyro-models.git
      - py
      - sklearn
      - sklearn2
      - git+https://github.com/optuna/optuna.git
      - cma
      - cmaes
      - git+https://github.com/facebookresearch/nevergrad.git
      - git+https://github.com/facebook/Ax.git
      - git+https://github.com/bamos/block.git
      - git+https://github.com/sksq96/pytorch-summary.git
      - git+https://github.com/facebookresearch/higher.git
      - git+https://github.com/facebookresearch/FDR_scheduler.git
      - git+https://github.com/arogozhnikov/einops.git
      - eagerpy
      - pytorch-zoo
      - git+https://github.com/pfnet/pfio.git
      - git+https://github.com/pfnet/pytorch-pfn-extras.git
      - watermark
      - mlxtend
      - onnxconverter-common
      - skl2onnx
      - sklearn-pandas
      - git+https://github.com/williamFalcon/pytorch-complex-tensor.git
      - ase
      - importlib-resources
      - neptune-client
      - neptune-contrib
      - neptune-notebooks
      - neptune-mlflow
      - git+https://github.com/getkeops/keops.git
      - git+https://github.com/jeanfeydy/geomloss.git
      - git+https://github.com/fmfn/BayesianOptimization.git
      - git+https://github.com/jettify/pytorch-optimizer.git
      - git+https://github.com/jettify/pytorch-inspect.git
      - git+https://github.com/BorealisAI/advertorch.git
      - git+https://github.com/KevinMusgrave/pytorch-metric-learning.git
      - git+https://github.com/rtqichen/torchdiffeq
      - git+https://github.com/SystemsBioinformatics/stochpy.git
      - onnxmltools
      - onnxoptimizer
      - cftime
      - adabelief-pytorch==0.2.1
      - git+https://github.com/emaballarin/ebtorch.git
      - git+https://github.com/rwightman/pytorch-image-models.git
      - git+https://github.com/facebookresearch/qhoptim.git
      - git+https://github.com/ufoym/imbalanced-dataset-sampler.git
      - git+https://github.com/KieranWynn/pyquaternion.git
      - git+https://github.com/ispamm/hTorch.git
      - git+https://github.com/MKuranowski/aiocsv.git
      - git+https://github.com/szagoruyko/pytorchviz.git
      - git+https://github.com/TylerYep/torchinfo.git
      - git+https://github.com/huggingface/huggingface_hub.git
      - git+https://github.com/digantamisra98/Echo.git
      - git+https://github.com/bashtage/randomgen.git
      - git+https://github.com/niklexical/brc_pytorch.git
      - git+https://github.com/davidtvs/pytorch-lr-finder.git
      - git+https://github.com/facebookresearch/madgrad.git
      - typish
      - git+https://github.com/ramonhagenaars/nptyping.git
      - git+https://github.com/scardine/image_size.git
      - git+https://github.com/huggingface/accelerate.git
      - git+https://github.com/Cadene/pretrained-models.pytorch.git
      - git+https://github.com/emaballarin/pytorch-kfac.git
      - git+https://github.com/kosiokarchev/clipppy.git
      - git+https://github.com/sissa-data-science/DULY.git
      - git+https://github.com/wandb/pyrasite.git
      - git+https://github.com/lessw2020/Ranger21.git
      #
      - jupyter_http_over_ws
      - ml_collections
      - pynvml
      - git+https://github.com/FrancescoSaverioZuppichini/glasses.git
      - datasets
      - sacremoses
      - transformers
      - git+https://github.com/huggingface/nn_pruning.git
      - git+https://github.com/bethgelab/imagecorruptions.git
      - git+https://github.com/bethgelab/foolbox.git
      - git+https://github.com/pytorch/ort.git
      - pytorchfi
      - lckr-jupyterlab-variableinspector
      - onnxruntime-training
