name: RDDL

channels:
  # Keep sorted | Add at the bottom!
  - pytorch
  - pytorch-test
  - fastai
  - nvidia
  - defaults
  - conda-forge
  - gpytorch
  - dglteam
  - pyviz
  - plotly
  - bokeh
  - gurobi
  - mosek
  - oxfordcontrol
  - albumentations
  - comet_ml
  - cvxgrp
  - intel
  - nlesc
  - norse

dependencies:
  # CONDA PINNED
  - python=3.8.8
  - cudatoolkit=11.1
  - magma-cuda111=2.5.2
  - blas=*.*=mkl
  - opt_einsum=3.3
  - pillow=7.0 # Pillow-SIMD
  - parso=0.8.1

  # Important pins
  - numpy=1.19.5 # tensorflow: ==1.19.5
  - scipy>=1.6.1
  - pyyaml=5.3.1
  - tqdm=4.54.1
  - pyglet=1.5.0
  - fastapi=0.58.1
  - mypy=0.790
  - fasteners=0.15

  - visdom=0.1.8.9

  - cython-blis=0.7.4 # ThinC & friends <- start
  - cymem=2.0.5
  - murmurhash=1.0.5
  - preshed=3.0.5
  - pydantic=1.7.3 # fixed!
  - wasabi=0.8.2
  - srsly=2.4
  - catalogue=2.0.1
  - immutables=0.15 # <- end

  - pytorch=1.8
  - jpeg
  - torchvision=0.9
  - torchaudio=0.8
  - torchtext=0.9
  - torchcsprng=0.2
  - torchserve=0.3.1
  - torch-model-archiver=0.3.1
  - gpytorch=1.4
  - botorch=0.4
  - ignite>=0.4.4
  - captum=0.3.1
  - onnx=1.8.1
  - tensorboard=2.4.1
  - tensorboardx=2.1
  - tensorly>=0.5.1
  - dgl-cuda11.1>=0.6.0post1 # version still not available!
  - faiss-gpu>=1.7 # <- end

  - fastcore>=1.3.19 # <- Fast.ai & friends
  - fastprogress>=1
  - nbdev>=1.1.13
  - fastgpu>=1.0.1
  - fastscript>=1 # <- end

  - jupyterlab>=3.0.12 # Jupyter(Lab) & friends <- start
  - notebook>=6.3 # <- end

  - vaex>=4 # Vaex & friends <- start
  - vaex-core>=4
  - vaex-astro>=0.8
  - vaex-hdf5>=0.7
  - vaex-viz>=0.5
  - vaex-jupyter>=0.6
  - vaex-server>=0.4
  - vaex-ml>=0.9 # <- end

  - dvc>=2.0.7 # DVC & friends <- start
  - networkx>=2.4 # (dvc requires < 2.5) # <- end

  - comet_ml>=3.6

  # Mathematical otimization
  - gurobi>=9.1.1
  - MOSEK>=9.2.40

  # Catalyst & friends (versioned)
  - aio-pika>=6 # It will be downgraded! (expected)

  # TensorAnnotations
  - pytype>=2020.10.8

  # JAX Verify + CVXPY
  - cvxpy>=1.1.11
  - cvxpy-base>=1.1.11
  - ecos>=2.0.7.post1
  - osqp>=0.6.2
  - scs>=2.1.2

  # Dependency fixups (1)
  - idna=2.8
  - requests=2.22.0
  - yarl=1.4.2
  - virtualenv=16.7

  # Carefree Toolkits & co.
  - pathos>=0.2.7
  - black>=20.8b1
  - nb_black>=1.0.7
  - mlflow>=1.14.1

  # ATHENA
  - gpy=1.9.9
  - gpyopt=1.2.6

  # MackeLab
  - simpleeval>=0.9.10
  - blosc>=1.21
  - astunparse>=1.6.3 # tensorflow: ==1.6.3

  # BAAL
  - structlog>=21.1

  # TensorFlow & co. (pinned)
  - grpcio=1.34
  - wrapt=1.12.1
  - h5py=2.10
  - gast=0.4
  - google-pasta>=0.2
  - typeguard>=2.7
  - gin-config>=0.4

  # Some extras
  - streamlit>=0.78
  - altair>=2.3.0
  - boltons>=20.2.1
  - trampoline>=0.1.2
  - python-libsbml>=5.19
  - fastrlock>=0.5

  # Aesara and PyMC3
  - aesara>=2.0.2
  - pymc3>=3.11.1
  - theano-pymc>=1.1.2

  # TensorWerk
  - cloudpickle>=1.4
  - hdf5plugin>=2
  - python-lmdb>=0.94

  # Install easers
  - pip>=20.3.4
  - pip-tools>=5.5

  # Brain / Neuro / SNNs
  - norse>=0.0.6


  # CONDA FLOATING #
  - conda
  - mkl-service
  - mkl
  - mkl_fft
  - mkl_random
  - intel-openmp

  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - scikit-learn
  - scikit-optimize
  - skorch
  - seaborn
  - statsmodels
  - sympy
  - hdf5
  - sqlalchemy
  - pandas-summary
  - imbalanced-learn
  - scikit-plot

  - importlib_metadata # Install easers <- start
  - setuptools
  - wheel
  - pep517 # <- end

  - regex
  - future
  - psutil
  - sentencepiece
  - libjpeg-turbo
  - libpng
  - imageio

  - librosa

  - ipykernel # Jupyter & friends <- start
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_launcher
  - jupyterlab_server
  - nb_conda_kernels
  - nbclient
  - nbconvert
  - nbformat
  - widgetsnbextension
  - ipyparallel
  - jupyter_nbextensions_configurator # <- end

  - ipdb # Development aids / typing <- start
  - ptvsd
  - pylint
  - mypy_extensions
  - typed-ast # <- end

  - cffi
  - pybind11
  - swig

  - joblib
  - multiprocess

  - prompt_toolkit
  - wcwidth

  - click
  - gitpython
  - gql
  - nvidia-ml-py3
  - python-dateutil
  - shortuuid
  - six
  - watchdog
  - configparser
  - sentry-sdk
  - docker-pycreds
  - google-cloud-storage
  - boto3
  - azure-storage-blob

  - attrs
  - funcsigs
  - furl
  - humanfriendly
  - jsonschema
  - pathlib2
  - plotly
  - jinja2
  - pyparsing
  - pyjwt
  - requests-file
  - urllib3

  - shapely

  - nbval
  - multipledispatch

  - threadpoolctl
  - pluggy
  - more-itertools
  - iniconfig
  - pyparsing
  - packaging
  - toml
  - attrs
  - pytest
  - patsy
  - pytz
  - category_encoders
  - kiwisolver
  - cycler
  - pydot

  - alembic
  - cliff
  - colorlog
  - cmaes
  - bayesian-optimization

  - redis
  - redis-py
  - filelock
  - prometheus_client
  - pytz
  - googleapis-common-protos
  - pyasn1
  - pyasn1-modules
  - rsa
  - cachetools
  - google-auth
  - chardet
  - certifi
  - google-api-core
  - opencensus-context
  - opencensus
  - async-timeout
  - multidict
  - attrs
  - aiohttp
  - blessings
  - gpustat
  - pyrsistent
  - jsonschema
  - colorama
  - hiredis
  - aioredis
  - msgpack-python
  - msgpack-numpy
  - soupsieve
  - beautifulsoup4

  - oauthlib
  - pyzmq

  - frozendict

  - networkx

  - toolz
  - pyarrow
  - retrying
  - attrdict
  - pyhocon
  - atomicwrites
  - olefile
  - pycparser

  - numba
  - rdflib
  - googledrivedownloader

  - cxxfilt

  - bottleneck
  - numexpr
  - pytest-runner

  - cython

  - scikit-geometry

  - bravado-core # Neptune.ai & friends <- start
  - bravado
  - py3nvml
  - requests-oauthlib
  - websocket-client
  - hiplot
  - path.py # <- end

  # Catalyst & friends (extras) <- start
  - deprecation
  - python-daemon # <- end

  # ObJAX
  - parameterized

  # Misc: <- start
  - gputil
  - llvmlite
  - python-louvain # <- end

  - ipygany

  # Carefree Toolkits & co.
  - dill
  - tabulate

  # TensorFlow & co (unpinned)
  - termcolor
  - terminaltables
  - decorator
  - promise
  - dataclasses
  - portpicker
  - python-annoy

  # Some extras
  - twine
  - bottle
  - pypeln
  - gsutil
  - anytree

  # TensorFlow
  - absl-py # tensorflow: ==0.10 (may break ORTools)

  # TensorWerk
  - lmdb
  - xxhash
  - python-xxhash
  - rich

  # Wessel Bruinsma's stuff
  - python-slugify
  - xarray

  # Avalanche (ContinualAI)
  - typing_extensions
  - quadprog

  # FSDL
  - editdistance
  - flask
  - bandit
  - nltk
  - pycodestyle
  - pydocstyle
  - tornado
  - safety


  # PIP #
  - pip:
      # Sort by dependency (~ toposort)
      - opencv-python
      - py-spy
      - colorful
      - git+https://github.com/pytorch/contrib.git
      - graphviz
      - git+https://github.com/explosion/ml-datasets.git
      - https://storage.googleapis.com/jax-releases/cuda111/jaxlib-0.1.64+cuda111-cp38-none-manylinux2010_x86_64.whl
      - jax==0.2.10
      - git+https://github.com/explosion/thinc.git
      - omegaconf
      - test_tube
      - wandb
      - protobuf
      - onnxruntime-gpu
      - onnxruntime-tools
      - fsspec
      - git+https://github.com/PyTorchLightning/metrics.git
      - git+https://github.com/PyTorchLightning/pytorch-lightning.git
      - clearml
      - clearml-agent
      - clearml-session
      - git+https://github.com/openai/atari-py.git
      - git+https://github.com/openai/gym.git
      - git+https://github.com/PyTorchLightning/lightning-bolts.git
      - wget
      - git+https://github.com/pyro-ppl/pyro-api.git
      - git+https://github.com/pyro-ppl/pyro.git
      - makefun
      - git+https://github.com/emaballarin/numpyro.git
      - git+https://github.com/pyro-ppl/funsor.git
      - git+https://github.com/emaballarin/pyro-models.git
      - py
      - sklearn
      - sklearn2
      - git+https://github.com/optuna/optuna.git
      - cma
      - git+https://github.com/facebookresearch/nevergrad.git
      - typeguard
      - git+https://github.com/facebook/Ax.git
      - redis
      - google
      - https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
      - git+https://github.com/bamos/block.git
      - wolframclient
      - git+https://github.com/sksq96/pytorch-summary.git
      - git+https://github.com/facebookresearch/higher.git
      - git+https://github.com/facebookresearch/FDR_scheduler.git
      - git+https://github.com/google/neural-tangents.git
      - pgmpy
      - dm-tree
      - dm-env
      - chex
      - git+https://github.com/deepmind/dm-haiku.git
      - git+https://github.com/deepmind/rlax.git
      - git+https://github.com/deepmind/optax.git
      - git+https://github.com/arogozhnikov/einops.git
      - git+https://github.com/google/TensorNetwork.git
      - eagerpy
      - torchlayers
      - git+https://github.com/szymonmaszke/torchfunc.git
      - torchdata
      - pytorch-zoo
      - krbticket
      - git+https://github.com/pfnet/pfio.git
      - git+https://github.com/pfnet/pytorch-pfn-extras.git
      - git+https://github.com/cybertronai/autograd-lib.git
      - watermark
      - mlxtend
      - onnxconverter-common
      - skl2onnx
      - sklearn-pandas
      - git+https://github.com/williamFalcon/pytorch-complex-tensor.git
      - ase
      - git+https://github.com/google/flax.git
      - antlr4-python3-runtime
      - async_exit_stack
      - orjson
      - uvicorn
      - ujson
      - aiormq
      - dnspython
      - git+https://github.com/python-hyper/h11.git
      - websockets
      - httptools
      - uvloop
      - importlib-resources
      - neptune-client
      - neptune-contrib
      - neptune-notebooks
      - neptune-mlflow
      - git+https://github.com/catalyst-team/alchemy.git
      - git+https://github.com/catalyst-team/reaction.git
      - git+https://github.com/catalyst-team/catalyst.git
      - git+https://github.com/TezRomacH/safitty.git
      - git+https://github.com/getkeops/keops.git
      - git+https://github.com/jeanfeydy/geomloss.git
      - git+https://github.com/fmfn/BayesianOptimization.git
      - git+https://github.com/google/objax.git
      - git+https://github.com/deepmind/jraph.git
      - git+https://github.com/deepmind/jax_verify.git
      - git+https://github.com/locuslab/qpth.git
      - git+https://github.com/carefree0910/carefree-toolkit.git
      - git+https://github.com/carefree0910/carefree-data.git
      - git+https://github.com/carefree0910/carefree-ml.git
      - git+https://github.com/carefree0910/carefree-learn.git
      - git+https://github.com/jettify/pytorch-optimizer.git
      - git+https://github.com/jettify/ibreakdown.git
      - git+https://github.com/jettify/pytorch-inspect.git
      - git+https://github.com/mathLab/PyDMD.git
      - git+https://github.com/mathLab/ATHENA.git
      - git+https://github.com/bayesiains/nflows.git
      - git+https://github.com/mackelab/pyknos.git
      - git+https://github.com/mackelab/sbi.git
      - parameters
      - git+https://github.com/mackelab/mackelab-toolbox.git
      - git+https://github.com/BorealisAI/advertorch.git
      - git+https://github.com/pfnet/pfrl.git
      - git+https://github.com/GRAAL-Research/poutyne.git
      - record-keeper
      - git+https://github.com/KevinMusgrave/pytorch-metric-learning.git
      - git+https://github.com/rtqichen/torchdiffeq
      - git+https://github.com/emaballarin/torchsde.git
      - git+https://github.com/patrick-kidger/torchcde.git
      - git+https://github.com/patrick-kidger/torchcubicspline.git
      - git+https://github.com/patrick-kidger/signatory.git
      - git+https://github.com/SystemsBioinformatics/stochpy.git
      - comet-for-mlflow
      - flatbuffers
      - fire
      - keras2onnx
      - onnxmltools
      - git+https://github.com/onnx/optimizer.git
      - click-didyoumean
      - git+https://github.com/wesselb/plum.git
      - git+https://github.com/wesselb/fdm.git
      - git+https://github.com/wesselb/lab.git
      - git+https://github.com/wesselb/algebra.git
      - git+https://github.com/wesselb/neuralprocesses.git
      - git+https://github.com/wesselb/oilmm.git
      - git+https://github.com/chrsmrrs/k-gnn.git
      - cftime
      - netCDF4
      - git+https://github.com/gehring/fax.git
      - lz4
      - pygame
      - git+https://github.com/thu-ml/tianshou.git
      - adabelief-pytorch==0.2.1
      - git+https://github.com/emaballarin/ebtorch.git
      - git+https://github.com/rwightman/pytorch-image-models.git
      - git+https://github.com/cair/pyTsetlinMachine.git
      - git+https://github.com/facebookresearch/qhoptim.git
      - git+https://github.com/learnables/cherry.git
      - git+https://github.com/vballoli/nfnets-pytorch.git
      - git+https://github.com/ufoym/imbalanced-dataset-sampler.git
      - git+https://github.com/KieranWynn/pyquaternion.git
      - git+https://github.com/giorgiozannini/hTorch.git
      - git+https://github.com/TorchDrift/TorchDrift.git
      - git+https://github.com/MKuranowski/aiocsv.git
      - git+https://github.com/szagoruyko/pytorchviz.git
      - git+https://github.com/TylerYep/torchinfo.git
      - bidict
      - git+https://github.com/nengo/nengo.git
      - git+https://github.com/emaballarin/nengo-gui.git
      - git+https://github.com/nengo/pytorch-spiking.git
      - git+https://github.com/nengo/nengo-interfaces.git
      - git+https://github.com/emaballarin/nengolib.git
