name: RDDLean

channels:
  # Keep sorted | Add at the bottom!
  - pytorch
  - pytorch-test
  - fastai
  - nvidia
  - defaults
  - conda-forge
  - numba
  - gpytorch
  - dglteam
  - pyviz
  - plotly
  - bokeh
  - cvxgrp
  - HuggingFace
  - fastchan
  - comet_ml
  - intel
  - nlesc
  - ivanyashchuk

dependencies:
  # PINNED

  # System
  - python=3.9.13
  - blas=*.*=mkl

  # CUDA & co.
  - cudatoolkit=11.6
  - cuda-runtime=11.6
  - cuda-libraries>=11.6
  - cuda-libraries-dev>=11.6
  - cuda-cudart>=11.6
  - cuda-cudart-dev>=11.6
  - libcusparse>=11.6
  - libcusparse-dev>=11.6
  - cuda-nvcc=11.6
  - nccl>=2.12.12
  - cudnn>=8.4.1
  - magma-cuda116>=2.6.1

  # PyTorch stack
  - pytorch>=1.12.1
  - torchvision>=0.13.1
  - torchaudio>=0.12.1
  - torchtext>=0.13.1
  - torchserve>=0.6
  - torch-model-archiver>=0.6
  - torch-workflow-archiver>=0.2.4
  - gpytorch>=1.8.1
  - ignite>=0.4.9
  - captum>=0.5
  - accimage>=0.2
  - torchdata>=0.4.1
  - torchdistx>=0.2
  - torchdistx-cc>=0.2
  - urllib3>=1.25 # Do not edit!

  # Vaex
  - vaex>=4.11.1 # Latest
  - vaex-core>=4.11.1 # Same as vaex
  - vaex-astro>=0.8.3 # Do not edit!
  - vaex-hdf5>=0.10 # Do not edit!
  - vaex-viz>=0.5 # Do not edit!
  - vaex-jupyter>=0.6 # Do not edit!
  - vaex-server>=0.6 # Do not edit!
  - vaex-ml>=0.9 # Do not edit!

  # Pillow for Pillow-SIMD
  - pillow=9.0.0

  # FFIs
  - cffi>=1.10.0 # Do not edit!

  # Misc
  - opt_einsum>=3.3
  - onnx>=12
  - tensorboard>=2.10
  - tensorboardx>=2.5
  - dgl-cuda11.6>=0.9
  - jupyterlab>=3.4.5
  - notebook>=6.4.12
  - black>=21.11b0 # Do not edit!
  - nb_black>=1.0.7
  - mlflow>=1.28
  - pip>=20.3.4 # Do not edit!
  - pip-tools>=5.5 # Do not edit!
  - numba=0.53.1 # Keep in sync with pip requirements!
  - fastprogress>=1 # Do not edit!
  - jedi>=0.18.1
  - typeguard>=2.11.1 # Do not edit!
  - jupytext>=1.14
  - nbformat>=5.4
  - nbclient>=0.6.7
  - comet_ml>=3.31.11

  # DeepRobust
  - numpy=1.23.2 # UPDATE FREQUENTLY!
  - scipy>=1.8.1 # Do not edit!
  - matplotlib>=3.1.1 # Do not edit!
  - scikit-learn>=0.22.1 # Do not edit!
  - scikit-image>=0.0 # Do not edit!
  - networkx>=2.4 # Do not edit!
  - texttable>=1.6.2 # Do not edit!
  - gensim=3.8.* # KEEP IN SYNC WITH DeepRobust requirements

  # Install easers
  - importlib_metadata>=4.8.2 # Sync with https://github.com/lf1-io/padl/blob/b261d51a0be9ff9989b76009913e226894b71a39/requirements.txt#L5

  # Extras
  - tqdm>=3.0 # Do not edit!
  - protobuf>=3 # Do not edit!
  - jsonschema=3.2 # Sync with pip requirements!

  # UNPINNED

  # System
  - conda
  - mkl-service
  - mkl
  - mkl_fft
  - mkl_random
  - intel-openmp

  # Install easers
  - setuptools
  - wheel
  - pep517

  # Scientific stack
  - pandas
  - scikit-optimize
  - seaborn
  - statsmodels
  - sympy
  - scikit-plot
  - scikit-geometry

  # Jupyter
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab_launcher
  - jupyterlab_server
  - nb_conda_kernels
  - nbconvert
  - widgetsnbextension
  - jupyter_contrib_nbextensions
  - ipyparallel
  - jupyter_nbextensions_configurator
  - ipygany
  - nbval

  # FFIs
  - pybind11
  - swig

  # Typing / Development aids
  - mypy
  - ipdb
  - ptvsd
  - pylint
  - mypy_extensions
  - typed-ast
  - typing_extensions

  # Misc
  - async-timeout
  - atomicwrites
  - attrdict
  - attrs
  - azure-storage-blob
  - bayesian-optimization
  - boto3
  - bravado
  - bravado-core
  - cachetools
  - category_encoders
  - certifi
  - chardet
  - click
  - cmaes
  - colorama
  - colorlog
  - configparser
  - cython
  - dataclasses
  - decorator
  - docker-pycreds
  - faiss-gpu
  - filelock
  - frozendict
  - funcsigs
  - future
  - gitpython
  - google-api-core
  - google-auth
  - google-cloud-storage
  - googleapis-common-protos
  - gpustat
  - h5py
  - hdf5
  - hiplot
  - imageio
  - imbalanced-learn
  - iniconfig
  - jinja2
  - joblib
  - jpeg
  - libjpeg-turbo
  - libpng
  - more-itertools
  - msgpack-numpy
  - msgpack-python
  - multidict
  - multipledispatch
  - multiprocess
  - numexpr
  - nvidia-ml-py3
  - oauthlib
  - olefile
  - packaging
  - pandas-summary
  - parso
  - path.py
  - pathlib2
  - plotly
  - prometheus_client
  - prompt_toolkit
  - psutil
  - py3nvml
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyjwt
  - pyparsing
  - pyrsistent
  - pytest
  - pytest-runner
  - python-dateutil
  - pytz
  - pyzmq
  - regex
  - requests-file
  - requests-oauthlib
  - rsa
  - six
  - threadpoolctl
  - toml
  - toolz
  - visdom
  - watchdog
  - wcwidth
  - websocket-client

  # Pip dependencies
  - prettytable
  - pyyaml
  - autopage
  - cerberus
  - cliff
  - cmd2
  - deprecation
  - distlib
  - fastrlock
  - flatbuffers
  - furl
  - humanfriendly
  - idna
  - jsonpointer
  - makefun
  - munch
  - pathtools
  - pbr
  - promise
  - py-cpuinfo
  - pydot
  - pyhocon
  - pyperclip
  - rfc3987
  - ruamel.yaml
  - ruamel.yaml.clib
  - sentry-sdk
  - shortuuid
  - stevedore
  - termcolor
  - urwid
  - virtualenv
  - webcolors
  - xxhash
  - python-xxhash
  - yaspin

  # init.sh dependencies (not included in pip dependencies)
  - googledrivedownloader
  - rdflib
  - yacs

  # Migrated from pip (in init.sh)
  - contextlib2
  - pyrser
  - tokenizers
  - jsonargparse
  - rich

  # PyTorch Lightning & co.
  - requests
  - aiohttp
  - fsspec
  - docstring_parser
  - pydeprecate
  - gcsfs

  # MosaicML | FFCV
  - pkg-config
  - compilers
  - opencv
  - terminaltables
  - assertpy
  - jsonpatch

  # PADL
  - astunparse

  # Extras
  - tzlocal

  # Y0
  - pygraphviz
  - tabulate
